
syntax = "proto3";
package user;
message User {
  string id = 1;
  string email = 2;
}
message SignUpDto {
  string username = 1;
  string email = 2;
  string password = 3;
}
message SignInDto {
  string email = 1;
  string password = 2;
}
message CheckOtpDto {
  string email = 1;
  string otpCode = 2;
}
message AuthResponse {
  string message = 1;
}
message VerifyOtpResponse{
 string  message =1;
 string jwtToken = 2; 
}
message Empty {}

message ValidateJWtTokenDto{
  string token=1;
}
message UserPayload {
  string id=3;
  string email=1;
  string username=2;
}
service AuthService {
  rpc SignUp(SignUpDto) returns (AuthResponse);
  rpc SignIn(SignInDto) returns (AuthResponse);
  rpc CheckOtp(CheckOtpDto) returns (VerifyOtpResponse);
  rpc ValidateJwtToken(ValidateJWtTokenDto) returns (UserPayload);
}